### ISSUE TITLE
Adding Scoring Settings In Calculate Projections?

### ISSUE THREAD

**Issue by MechanicalFox** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#32]
Is it possible to add additional scoring settings to the Calculate Projections? For instance, in the Scoring Settings under QB, there are 300 Yd, 350 Yd, and 400 Yd passing bonuses, however my league uses 250 Yd, 300 Yd, and 350 Yd bonuses. Is it possible to add to the Scoring Settings to include the 250 Yd bonus? This is just one example. My league also uses WR receiving yard bonuses which are not included in the Scoring Settings.

**Comment by MrDAndersen** [comment]
Receiving  bonuses have been added. We don't have projections for 250yd passing games

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
