### ISSUE TITLE
FantasyPros Scrape fails for all positions but DST

### ISSUE THREAD

**Issue by jeremypernicek** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#35]
Scrape summary is below. The FantasyPros scrape is failing for nearly all positions when running the scrape script below. 

myScrapeData <- runScrape(week = 0, season = 2016, 
                  analysts = c(-1, 3, 4, 5, 6, 7, 9, 11, 12, 13, 14, 15, 22, 23, 17, 18, 19, 20, 28), 
                  positions = c("QB", "RB", "WR", "TE", "K", "DST"), 
                  fbgUser = "my_username", fbgPwd = "my_password")

Scrape Summary:
     QB :
        Successfully: CBS Average, Yahoo Sports, ESPN, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, Bob Henry, Jason Wood, FantasySharks, FantasyData 
        Failed: FantasyPros, EDS Football, FantasyFootballNerd, WalterFootball 
     RB :
        Successfully: CBS Average, Yahoo Sports, ESPN, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, Bob Henry, Jason Wood, FantasySharks, FantasyFootballNerd, WalterFootball, FantasyData 
        Failed: FantasyPros, EDS Football 
     WR :
        Successfully: CBS Average, Yahoo Sports, ESPN, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, Bob Henry, Jason Wood, FantasySharks, FantasyFootballNerd, WalterFootball, FantasyData 
        Failed: FantasyPros, EDS Football 
     TE :
        Successfully: CBS Average, Yahoo Sports, ESPN, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, Bob Henry, Jason Wood, FantasySharks, FantasyFootballNerd, WalterFootball, FantasyData 
        Failed: FantasyPros, EDS Football 
     K :
        Successfully: CBS Average, Yahoo Sports, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, FantasySharks, FantasyFootballNerd, WalterFootball, FantasyData 
        Failed: FantasyPros, Mike Herman 
     DST :
        Successfully: CBS Average, Yahoo Sports, NFL, FOX Sports, FFToday, David Dodds, Maurile Tremblay, FantasySharks, FantasyFootballNerd, FantasyData 
        Failed: NA

**Comment by jeremypernicek** [comment]
Here's what I get when just trying to scrape FantasyPros QB's

> myScrapeData <- runScrape(week = 0, season = 2016, analysts = c(9), positions = c("QB"), fbgUser = NULL, fbgPwd = NULL)

Retrieving player data 
Empty data table retrieved from
 https://www.fantasypros.com/nfl/projections/qb.php?week=draft 
=================
Scrape Summary:
	 QB :
		Successfully:  
		Failed: FantasyPros 
Warning message:

**Comment by dadrivr** [comment]
Works for me. What do you get when you run `sessionInfo()`?

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
