### ISSUE TITLE
Error - getProjections

### ISSUE THREAD

**Issue by cthom110** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#42]
Hi - I'm getting an error when I try to use the getProjections function (In this example, I'm using the addin to trigger the function, but I get the same error when I do it manually):

> myProjections <- getProjections(scrapeData=runScrape(week = 6, season = 2016, analysts = c(3), positions = c("QB")), avgMethod = "average", leagueScoring = userScoring, vorBaseline, vorType, teams = 12, format = "standard", mflMocks = -1, mflLeagues = -1, adpSources = NULL)
> # Retrieving player data 
> 
> Scrape Summary:
>      QB :
>         Successfully: Yahoo Sports 
>         Failed: NA 

Retrieving ECR ranks for position  
Error in data.table::setnames(rnks, cNames) : 
  Can't assign 7 names to a 8 column data.table

Not sure what to make of this...any thoughts?
Thanks

**Comment by MrDAndersen** [comment]
This should be fixed now. Please update the package or install version 0.1.91 of the tar file

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
