### ISSUE TITLE
Weekly projections not working on 0.1.91

### ISSUE THREAD

**Issue by blacknred0** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#43]
I am not sure if I am doing something wrong or what, so, I am going to label this as an issue for now.

Here is what I have done, now if I run the getProjections() function, the result is blank (see image further below)

``` R
myScrapeData <- runScrape(week = 6, season = 2016, analysts = c(-1, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19), positions = c("QB", "RB", "WR", "TE", "K", "DST", "DL", "LB", "DB"), fbgUser = NULL, fbgPwd = NULL)
myProjections <- getProjections(myScrapeData, avgMethod = "average", leagueScoring = userScoring, vorBaseline, vorType, teams = 10, format = "standard", mflMocks = -1, mflLeagues = -1, adpSources = c("ESPN"))
```

Results
<img width="828" alt="screen shot 2016-10-18 at 11 54 25 am" src="https://cloud.githubusercontent.com/assets/10933631/19487886/402fb88a-952a-11e6-93b9-42de5484eeb3.png">
Log

> Calculating risk                                                     
> 
> Listening on http://127.0.0.1:3569
> 
> Warning messages:
> 1: Weekly ECR ranks not available for IDP 
> 2: Weekly ECR ranks not available for IDP 
> 3: Weekly ECR ranks not available for IDP 
> 4: Weekly overall rankings not available

Thoughts?

**Comment by eruizmateo** [comment]
Same deal here.

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
