### ISSUE TITLE
Error when running runScrape

### ISSUE THREAD

**Issue by hueykwik** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#45]
I tried running a scrape on the 2016 season for all the free projection sources. The script ran for a while (~15 minutes?) and then I got the following error. What's going on? The error message makes it hard to know what's going on, which is frustrating. 

`myScrapeData <- runScrape(week = 0, season = 2016, analysts = c(-1, 3, 4, 5, 6, 7, 9, 17, 18, 19, 20, 28), positions = c("QB", "RB", "WR", "TE", "K", "DST"), fbgUser = NULL, fbgPwd = NULL)`

```
Retrieving player data 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=80 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=120 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=160 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=160 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=200 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=240 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=280 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=320 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=360 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=400 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=160 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=200 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=240 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=280 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=320 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=360 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=400 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=440 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=480 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=520 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=160 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=200 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=240 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=280 
Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for 'xmlNamespaceDefinitions' applied to an object of class "NULL"
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by blacknred0** [comment]
I have this happened some times as well. Not sure if it is the scripts or the sites. In the end, if I keep trying long enough it works.

On Oct 21, 2016, at 7:05 PM, hueykwik <notifications@github.com> wrote:

I tried running a scrape on the 2016 season for all the free projection sources. The script ran for a while (~15 minutes?) and then I got the following error. What's going on? The error message makes it hard to know what's going on, which is frustrating.

myScrapeData <- runScrape(week = 0, season = 2016, analysts = c(-1, 3, 4, 5, 6, 7, 9, 17, 18, 19, 20, 28), positions = c("QB", "RB", "WR", "TE", "K", "DST"), fbgUser = NULL, fbgPwd = NULL)

Retrieving player data 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=80 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=120 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=0&startIndex=160 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=160 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=200 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=240 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=280 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=320 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=360 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=2&startIndex=400 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=160 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=200 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=240 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=280 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=320 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=360 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=400 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=440 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=480 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=4&startIndex=520 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=0 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=40 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=80 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=120 
Removing columns after column 13 
Got more columns in data than number of columns specified by names from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=160 
Removing columns after column 13 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=200 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=240 
Empty data table retrieved from
 http://games.espn.go.com/ffl/tools/projections?&slotCategoryId=6&startIndex=280 
Error in UseMethod("xmlNamespaceDefinitions") : 
  no applicable method for 'xmlNamespaceDefinitions' applied to an object of class "NULL"
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
