### ISSUE TITLE
Problem installing latest package (ffanalytics_0.1.91.tar.gz)

### ISSUE THREAD

**Issue by pdbartsch** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#46]
When installing the latest package, I had issues on a Windows machine.  There was a no such file or directory exists error for the following file:

`...dadrivr-FantasyFootballAnalyticsR53c3723/R Markdown/SubcriptionAccuracy/subscriptionAccuracy_cache/markdown_phpextra+backtick_code_blocks/unnamed-chunk-1_af5e2a896358b9ccbc8241e876b9ce5c.RData`

I attempted installation using devtools and also by downloading the file locally first.  

The ffanalytics_0.1.9.tar.gz package installed just fine.

I'm happy to provide more details if you'd like.

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
