### ISSUE TITLE
Problem Installing ffanalytics Package

### ISSUE THREAD

**Issue by herkyonparade** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#47]
Hello -

I'm unable to download your package. The code and error are below. Please let me know what I need to do differently. Thanks for all your work!

`library("devtools")`
`library("rstudioapi")`

`devtools::install_github(repo = "dadrivr/FantasyFootballAnalyticsR",  subdir = "R Package/ffanalytics")`

>Downloading GitHub repo dadrivr/FantasyFootballAnalyticsR@master
from URL https://api.github.com/repos/dadrivr/FantasyFootballAnalyticsR/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/JOHN~1.COR/AppData/Local/Temp/RtmpKid3s6/devtools3688383f6eed/dadrivr-FantasyFootballAnalyticsR-53c3723/R Markdown/SubcriptionAccuracy/subscriptionAccuracy_cache/markdown_phpextra+backtick_code_blocks/unnamed-chunk-1_af5e2a896358b9ccbc8241e876b9ce5c.RData': No such file or directory

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
