### ISSUE TITLE
Yahoo Scraping Isnt Working

### ISSUE THREAD

**Issue by Deom23** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#48]
When trying to scrape projections from Yahoo, it fails, saying it returned empty tables.

**Comment by Langusmon** [comment]
Any update on this? I really need this functionality back. Thanks again.

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
