### ISSUE TITLE
Issue failed to load external entity

### ISSUE THREAD

**Issue by parkercoelho** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#51]
R Version 3.3.3 and R Studio version 1.1.447 

I click Addins at the top > Calculate Projections > fill out everything and run the following: 

myProjections <- getProjections(scrapeData=runScrape(week = 0, season = 2018, analysts = c(4, 9), positions = c("QB")), avgMethod = "average", leagueScoring = userScoring, vorBaseline, vorType, teams = 10, format = "standard", mflMocks = -1, mflLeagues = -1, adpSources = c("CBS", "ESPN", "FFC", "MFL", "NFL", "Yahoo"))
Retrieving player data 
Operation in progressfailed to load external entity "http://football.myfantasyleague.com/2018/export?TYPE=players&L=&W=0&JSON=0&DETAILS=1"
Error: 1: Operation in progress2: failed to load external entity "http://football.myfantasyleague.com/2018/export?TYPE=players&L=&W=0&JSON=0&DETAILS=1"

I am not sure why I am receiving that error. Anyone know how to fix this?

**Comment by isaactpetersen** [comment]
See the latest version of the app here: https://github.com/FantasyFootballAnalytics/ffanalytics
