### ISSUE TITLE
Reposting Issue from other repo.

### ISSUE THREAD

**Issue by gheemony** [FantasyFootballAnalytics/FantasyFootballAnalyticsR#54]
I have found the following issues with projection sources retrieved using scrape_data for season = 2019 and week = 0:

ESPN: No data is scraped. Projections are publicly available. Likely a scraping issue.

FantasyData: No data is scraped. The free projections are for a limited number of players; full projections are available only with a paid subscription. I suspect this is no longer a valid public data source.

FleaFlicker: No data is scraped. A free membership is required to access projections. This may simply require a revision to incorporate login with credentials.

FantasyFootballNerd: The scraped data is incorrect. For example, Calvin Johnson is projected as the #1 WR. It appears that free projections are available, so this may just require fixing the script.

WalterFootball: The projections for most positions don't include TD projections. I couldn't find projections on the website in HTML, so I couldn't determine if this is an error or if WF doesn't project TDs (which makes the projections much less useful).

Thanks!

**Comment by spcoventry** [comment]
I know that ESPN is redoing their sight right now, and that probably has
broken the old scraper function.

**Comment by isaactpetersen** [comment]
We'll use the issue posted in the ffanalytics app repo: https://github.com/FantasyFootballAnalytics/ffanalytics/issues/30
